---

# pb.docker.yml

- hosts: docker
  user: root
  become: true
  vars: 
      ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: copy ssh keys
      # https://stackoverflow.com/a/48882051
      authorized_key:
        user: root
        key: https://github.com/{{ item }}.keys
        comment: '{{ item }}'
      ignore_errors: yes
      with_items:
        - igami
        - stikkx
        - leon2225
        - mattn81

  roles:
#    - common
#    - role: "nickjj.docker"
#      tags: ["docker"]
    - role: vaultwarden