---
# tasks file for vaultwarden
- name: Ensure docker modul is installed
  pip:
    name: docker

- name: Create vaultwarden container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    state: started
    ports: 80:80
    volumes:
     - /data/
