all:
  vars:
    links: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
  children:
    space.local:
      children:
        computer:
          children:
            workstation:
              hosts:
                jupiter:
                  description: links
                saturn:
                  description: rechts
            laptop:
              hosts:
                uranus:
                  description: Laptop
            # netbook:
            #   hosts:
            #     merkur:
            #       description: Netbook
          vars:
            backup: /home/
        # printers:
        #   hosts:
        #     epson:
        #       state: unmanaged
        #     IBM:
        #       state: unmanaged
      hosts:
        # spaceapi:
        ganymed:
          description: octoprint
          backup: /opt/octoprint/.octoprint/
        # halley:
        #   description: NAS
      vars:
        domain: space.local
    one-1.4830.org:
      hosts:
        forum:
          ansible_host: forum.makerspace-gt.de
          backup: /var/discourse/shared/standalone/backups/
        git:
          ansible_host: git.makerspace-gt.de
          backup:
            - /etc/gitlab/gitlab-secrets.json
            - /etc/gitlab/gitlab.rb
            - /var/opt/gitlab/backups/
        ipa:
          ansible_host: ipa.makerspace-gt.de
          ipv4: 192.251.226.18
          ipv6: 2a06:e881:1700:1:0:c0ff:fefb:e212
          backup:
            - /etc/ipsilon/idp/
            - /usr/share/ipsilon/
            - /var/lib/ipa/backup/
            - /var/lib/ipsilon/
        # huginn:
        #   dns: huginn.makerspace-gt.de
    lima-city.de:
      hosts:
        wordpress:
           backup: /home/webpages/lima-city/makerspace-gt/wordpress_de-2017-11-08-9d823b/
        nextcloud:
          backup: /home/webpages/lima-city/makerspace-gt/nextcloud-2019-03-12-e05b61/
      vars:
        ansible_host: makerspace-gt.lima-ssh.de
        ansible_user: makerspace-gt