all:
  vars:
    links: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
  children:
    space.local:
      children:
        computer:
          children:
            workstation:
              hosts:
                jupiter:
                  description: links
                saturn:
                  description: rechts
            laptop:
              hosts:
                uranus:
                  description: Laptop
            netbook:
              hosts:
                merkur:
                  description: Netbook
        printers:
          hosts:
            epson:
              state: unmanaged
            IBM:
              state: unmanaged
      hosts:
        spaceapi:
        ganymed:
          description: octoprint
      vars:
        FQDN: space.local
    one-1.4830.org:
      hosts:
        forum:
          ansible_host: forum.makerspace-gt.de
        git:
          dns:
            - git.makerspace-gt.de
            - makergt-01.4830.org
        ipa:
          ansible_host: ipa.makerspace-gt.de
          ipv4: 192.251.226.18
          ipv6: 2a06:e881:1700:1:0:c0ff:fefb:e212
        huginn:
          dns: huginn.makerspace-gt.de
    lima-city.de:
      hosts:
        wordpress:
        nextcloud: