---
- name: Install FreeIPA Server
  hosts: ipa
  become: yes

  vars:
    ipaadmin_password: m:;6D$k,n.:4[,Zn5Y!{,mNYx8XoqB"k
    ipadm_password: f2)R`T{2[&z5;g&FHc&q6x%SZSn]G/eG
    ipaserver_domain: makerspace-gt.de
    ipaserver_hostname: "ipa.{{ ipaserver_domain }}"
    ipaserver_realm: "{{ ipaserver_domain|upper }}"





  pre_tasks:
    - command:
        cmd: "hostnamectl set-hostname {{ ipaserver_hostname }}"
    - file: 
        path: /etc/hosts
        state: absent
    - copy:
        content: "{{ ansible_default_ipv4.address }} {{ ipaserver_hostname }}"
        dest: /etc/hosts

  roles:
#   - role: sethostname
  - role: ipaserver
#   - role: ipsilon
#   - role: freeipa-letsencrypt

  tasks:
    # https://ipsilon-project.org/doc/quickstart-ipa.html
    - yum:
        name:
        - ipsilon
        - ipsilon-infosssd
        - ipsilon-saml2
        - ipsilon-authgssapi
        - ipsilon-tools-ipa
    - file:
        src: /etc/krb5.keytab
        dest: /etc/httpd/conf/ipa.keytab
        state: link
        # https://www.freeipa.org/page/Kerberos
    - command:
        cmd: ipsilon-server-install --ipa=yes --info-sssd=yes --form=yes
    - file: 
        path: /etc/httpd/conf.d/ssl.conf
        state: absent
    - command:
        cmd: sed -i 's/\<SSL/NSS/' /etc/ipsilon/idp/idp.conf
    - service:
        name: httpd
        state: restarted

    # https://github.com/freeipa/freeipa-letsencrypt
    - yum: 
        name: 
          - epel-release
          - dnf
          - git
    - git:
        repo: https://github.com/freeipa/freeipa-letsencrypt.git
        dest: /root/ipa-le
        update: no
    - command: 
        cmd: git checkout 601f03b147b34871ddb0655e898541c179b57431
        chdir: /root/ipa-le
    - lineinfile:
        path: /root/ipa-le/renew-le.sh
        regexp: '^EMAIL='
        line: EMAIL="info@makerspace-gt.de"
    - lineinfile:
        path: /root/ipa-le/renew-le.sh
        regexp: '^#?cd "\$WORKDIR"'
        line: cd "$WORKDIR"
    - command:
        cmd: kinit -k -t /etc/krb5.keytab
    - command:
        cmd: /root/ipa-le/setup-le.sh
      when: vagrant is undefined
    - cron:
        name: "check letsencrypt certificate"
        minute: "0"
        hour: "0"
        job: "/root/ipa-le/renew-le.sh"