---
- name: add key
  apt_key:
    url: https://syncthing.net/release-key.txt

- name: add repository
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    filename: syncthing

- name: install
  apt:
    name:
      - syncthing